### ISSUE TITLE
Это не vue подход: unchecking on delete

### ISSUE THREAD

**Issue by arku31** [ZmoNkk/checkout#1]
https://github.com/ZmoNkk/checkout/blob/8404607281c46631732304dcecf0e1ba3414a51a/src/components/vcart.vue#L82

Вероятно стоило добавить в главный массив items еще одно свойство - is_checked, которое можно выставлять в false после успешного удаления, а не работать с DOM.

**Comment by ZmoNkk** [comment]
Поправил.
