### ISSUE TITLE
Почему это не computed?

### ISSUE THREAD

**Issue by arku31** [ZmoNkk/checkout#2]
https://github.com/ZmoNkk/checkout/blob/8404607281c46631732304dcecf0e1ba3414a51a/src/components/vcart.vue#L106

**Comment by ZmoNkk** [comment]
Согласен, здесь необходимо использовать именно computed, т.к. метод getTotal считал total и приходилось вызывать getTotal() руками, что обновить total.  Чтобы переменная оставалась реактивной без лишних костылей она должна быть computed в данном случае.
